# Generated by Django 3.2.4 on 2021-06-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=1000)),
                ('auther', models.CharField(max_length=1000)),
                ('VideoName', models.CharField(max_length=1000)),
                ('date_download', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
